name: revin
description: "Revin - Smart Market Analysis for Farmers"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  flutter_animate: ^4.2.0
  lottie: ^3.3.1
  provider: ^6.1.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  http: ^1.1.0
  dio: ^5.3.2
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.1.0
  intl: ^0.20.2
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
