// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKLeJWBjZod_y-3SAuwqJdVKbw_80tDxI',
    appId: '1:397785905273:web:6d274de2e1f27d3a6d3ca8',
    messagingSenderId: '397785905273',
    projectId: 'proj-ccb08',
    authDomain: 'proj-ccb08.firebaseapp.com',
    storageBucket: 'proj-ccb08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUxa3mc-Qe62x8M2vFSD-P3yBNY5g7Zf0',
    appId: '1:397785905273:android:c285e6045bdb8ad76d3ca8',
    messagingSenderId: '397785905273',
    projectId: 'proj-ccb08',
    storageBucket: 'proj-ccb08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUxa3mc-Qe62x8M2vFSD-P3yBNY5g7Zf0',
    appId: '1:397785905273:ios:c285e6045bdb8ad76d3ca8',
    messagingSenderId: '397785905273',
    projectId: 'proj-ccb08',
    storageBucket: 'proj-ccb08.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUxa3mc-Qe62x8M2vFSD-P3yBNY5g7Zf0',
    appId: '1:397785905273:ios:c285e6045bdb8ad76d3ca8',
    messagingSenderId: '397785905273',
    projectId: 'proj-ccb08',
    storageBucket: 'proj-ccb08.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
